name = "otphaven"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[build]
command = "bun install && bun run build"

[build.upload]
format = "service-worker"

[[build.upload.rules]]
type = "ESModule"
globs = ["**/*.js"]
fallthrough = true
